[project]
name = "filesystem-client"
version = "0.0"
requires-python = "==3.12.*"
dependencies = ["ops"]

[tool.repository]
libraries = [
    "operator-libs-linux.apt",
    "operator-libs-linux.systemd",
]
